server:
  port: 8087

spring:
  application:
    name: notification-service

  config:
    import: optional:configserver:http://config-server:8888

  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 3000
        multiplier: 1.5

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://discovery-service:8761/eureka}
  instance:
    prefer-ip-address: true