events {}

http {

    upstream api_gateway {
        server api-gateway:8080;
    }

    upstream login_service {
        server login-service:8081;
    }

    upstream content_service {
        server content-service:9002;
    }

    upstream analytics_service {
        server analytics-service:8088;
    }

    upstream notification_service {
        server notification-service:8087;
    }

    server {
        listen 80;

        # API Gateway (main entry)
        location / {
            proxy_pass http://api_gateway;
        }

        location /login/ {
            proxy_pass http://login_service/;
        }

        location /content/ {
            proxy_pass http://content_service/;
        }

        location /analytics/ {
            proxy_pass http://analytics_service/;
        }

        location /notification/ {
            proxy_pass http://notification_service/;
        }
    }
}
