server:
  port: 9002

spring:
  application:
    name: content-service

  config:
    import: optional:configserver:http://localhost:8888

  servlet:
    multipart:
      enabled: true
      max-file-size: 6000MB
      max-request-size: 6000MB

logging:
  level:
    org.springframework.web.cors: DEBUG
    org.springframework.security: DEBUG

minio:
  url: http://localhost:9100
  access-key: raju123345
  secret-key: rju456789544
  bucket: lms12345

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}

  instance:
    prefer-ip-address: true
