server:
  port: 8888

spring:
  application:
    name: config-server

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
         search-locations: file:/C:/DLMS/DLMS/dlms/services/DbConfig/src/main/resources/config