spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    root: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  
